{filters: [{direction: Inbound, dst_ip: null, dst_port: null, operation: Include,
      protocol: null, src_ip: null, src_port: null}], rules: [{ports: [80, 8080, 8888],
      protocol: HTTP}, {ports: [443], protocol: HTTPS}, {ports: [8080], protocol: HTTP-ALT},
    {ports: [8443], protocol: HTTPS-ALT}, {ports: [25], protocol: SMTP}, {ports: [
        110], protocol: POP3}, {ports: [143], protocol: IMAP}, {ports: [993], protocol: IMAPS},
    {ports: [995], protocol: POP3S}, {ports: [3306], protocol: MySQL}, {ports: [5432],
      protocol: PostgreSQL}, {ports: [27017], protocol: MongoDB}, {ports: [6379],
      protocol: Redis}, {ports: [22, 1, 2, 10], protocol: SSH}, {ports: [3389], protocol: RDP},
    {ports: [5900], protocol: VNC}, {ports: [445], protocol: SMB}, {ports: [548],
      protocol: AFP}, {ports: [873], protocol: Rsync}, {ports: [389], protocol: LDAP},
    {ports: [636], protocol: LDAPS}, {ports: [53], protocol: DNS}, {ports: [67, 68],
      protocol: DHCP}, {ports: [123], protocol: NTP}, {ports: [161], protocol: SNMP},
    {ports: [5060], protocol: SIP}, {ports: [5061], protocol: SIPS}, {ports: [500,
        4500], protocol: IPSec}, {ports: [1194], protocol: OpenVPN}, {ports: [1723],
      protocol: PPTP}, {ports: [21], protocol: FTP}, {ports: [69], protocol: TFTP},
    {ports: [514], protocol: Syslog}, {ports: [631], protocol: IPP}, {ports: [1111],
      protocol: test}]}
