export const NAME_TO_ISO_MAP: Record<string, string> = {
  Afghanistan: "AF",
  Angola: "AO",
  Albania: "AL",
  "United Arab Emirates": "AE",
  Argentina: "AR",
  Armenia: "AM",
  Antarctica: "AQ",
  "Fr. S. and Antarctic Lands": "TF",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Burundi: "BI",
  Belgium: "BE",
  Benin: "BJ",
  "Burkina Faso": "BF",
  Bangladesh: "BD",
  Bulgaria: "BG",
  Bahamas: "BS",
  "Bosnia and Herz.": "BA",
  Belarus: "BY",
  Belize: "BZ",
  Bolivia: "BO",
  Brazil: "BR",
  Brunei: "BN",
  Bhutan: "BT",
  Botswana: "BW",
  "Central African Rep.": "CF",
  Canada: "CA",
  Switzerland: "CH",
  Chile: "CL",
  China: "CN",
  "Côte d'Ivoire": "CI",
  Cameroon: "CM",
  "Dem. Rep. Congo": "CD",
  Congo: "CG",
  Colombia: "CO",
  "Costa Rica": "CR",
  Cuba: "CU",
  "N. Cyprus": "CY", // Note: Northern Cyprus might map to Cyprus 'CY'
  Cyprus: "CY",
  Czechia: "CZ",
  Germany: "DE",
  Djibouti: "DJ",
  Denmark: "DK",
  "Dominican Rep.": "DO",
  Algeria: "DZ",
  Ecuador: "EC",
  Egypt: "EG",
  Eritrea: "ER",
  Spain: "ES",
  Estonia: "EE",
  Ethiopia: "ET",
  Finland: "FI",
  Fiji: "FJ",
  "Falkland Is.": "FK",
  France: "FR",
  Gabon: "GA",
  "United Kingdom": "GB",
  Georgia: "GE",
  Ghana: "GH",
  Guinea: "GN",
  Gambia: "GM",
  "Guinea-Bissau": "GW",
  "Eq. Guinea": "GQ",
  Greece: "GR",
  Greenland: "GL",
  Guatemala: "GT",
  Guyana: "GY",
  Honduras: "HN",
  Croatia: "HR",
  Haiti: "HT",
  Hungary: "HU",
  Indonesia: "ID",
  India: "IN",
  Ireland: "IE",
  Iran: "IR",
  Iraq: "IQ",
  Iceland: "IS",
  Israel: "IL",
  Italy: "IT",
  Jamaica: "JM",
  Jordan: "JO",
  Japan: "JP",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Kyrgyzstan: "KG",
  Cambodia: "KH",
  "South Korea": "KR",
  Kosovo: "XK", // Kosovo ISO 3166-1 alpha-2 code is XK (user-assigned)
  Kuwait: "KW",
  Laos: "LA",
  Lebanon: "LB",
  Liberia: "LR",
  Libya: "LY",
  "Sri Lanka": "LK",
  Lesotho: "LS",
  Lithuania: "LT",
  Luxembourg: "LU",
  Latvia: "LV",
  Morocco: "MA",
  Moldova: "MD",
  Madagascar: "MG",
  Mexico: "MX",
  Macedonia: "MK",
  Mali: "ML",
  Myanmar: "MM",
  Montenegro: "ME",
  Mongolia: "MN",
  Mozambique: "MZ",
  Mauritania: "MR",
  Malawi: "MW",
  Malaysia: "MY",
  Namibia: "NA",
  "New Caledonia": "NC",
  Niger: "NE",
  Nigeria: "NG",
  Nicaragua: "NI",
  Netherlands: "NL",
  Norway: "NO",
  Nepal: "NP",
  "New Zealand": "NZ",
  Oman: "OM",
  Pakistan: "PK",
  Panama: "PA",
  Peru: "PE",
  Philippines: "PH",
  "Papua New Guinea": "PG",
  Poland: "PL",
  "Puerto Rico": "PR",
  "North Korea": "KP",
  Portugal: "PT",
  Paraguay: "PY",
  Palestine: "PS",
  Qatar: "QA",
  Romania: "RO",
  Russia: "RU",
  Rwanda: "RW",
  "W. Sahara": "EH",
  "Saudi Arabia": "SA",
  Sudan: "SD",
  "S. Sudan": "SS",
  Senegal: "SN",
  "Solomon Is.": "SB",
  "Sierra Leone": "SL",
  "El Salvador": "SV",
  Somaliland: "SO", // Somaliland often uses Somalia's code
  Somalia: "SO",
  Serbia: "RS",
  Suriname: "SR",
  Slovakia: "SK",
  Slovenia: "SI",
  Sweden: "SE",
  Swaziland: "SZ", // Eswatini
  Syria: "SY",
  Chad: "TD",
  Togo: "TG",
  Thailand: "TH",
  Tajikistan: "TJ",
  Turkmenistan: "TM",
  "Timor-Leste": "TL",
  "Trinidad and Tobago": "TT",
  Tunisia: "TN",
  Turkey: "TR",
  Taiwan: "TW",
  Tanzania: "TZ",
  Uganda: "UG",
  Ukraine: "UA",
  Uruguay: "UY",
  "United States": "US", // Corrected mapping
  Uzbekistan: "UZ",
  Venezuela: "VE",
  Vietnam: "VN",
  Vanuatu: "VU",
  Yemen: "YE",
  "South Africa": "ZA",
  Zambia: "ZM",
  Zimbabwe: "ZW",
};